---
AWSTemplateFormatVersion: '2020-02-24'
Description: 'A simple template intended to be run in us-west-2 with a Linux (2) distro.'
Resources:
  DB:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: 5
      StorageType: gp2
      DBInstanceClass: db.t3.micro
      DBName: wordpress
      Engine: MySQL
      MasterUsername: wordpress
      MasterUserPassword: w0rdpr355
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0e8c04af2729ff1bb # Linux (2), 
      InstanceType: t3.small
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash
            # Update all packages
            sudo su
            yum -y update
            # Install Apache PHP
            amazon-linux-extras install -y php7.2
            yum install -y httpd
            systemctl start httpd
            systemctl enable httpd
            echo "<?php phpinfo(); ?>" > /var/www/html/phpinfo.php
  S3:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: wp-michael-gat 

